name: picturelog
favicon: null
layout_spectrum: 0.45538124395534396
typography_spectrum: 0.17326
title: 'picturelog, a story in pictures'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-284671-14
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6919066694099456
  lightness: 0.9413504728581756
  saturation: 0.6445704360958189
  rhythmicContrast: 0.7076459103263915
purpose: []
